### ISSUE TITLE
How to handle ROM file without file_contexts.bin

### ISSUE THREAD

**Issue by qtopie** [iykequame/android_system_extraction_and_repack_tool#1]
Hi, I am trying to use your script to do the extraction and repacking  work. But there is no file_contexts.bin when I unzip this [update.zip](http://dl-res.flymeos.com/Firmware/Flyme/MX4_Pro/5.1.12.0G/intl_stable/20161220142736/e6abb713/update.zip) file.  ( A firmware for Meizu MX4 Pro)
How can I make it work?

**Comment by iykex** [comment]
@artificerpi will fix soon sir

**Comment by qtopie** [comment]
By the way, I've successfully extracted the rom_system files.

**Comment by iykex** [comment]
okay

**Comment by qtopie** [comment]
@iykequame  Thanks, and may I join to improve this tool?

**Comment by iykex** [comment]
@artificerpi sure, you can make a pull request

**Comment by iykex** [comment]
@artificerpi check the [latest update](https://github.com/iykequame/android_system_extraction_and_repack_tool/releases/tag/v1.8) , make few lines has been improved

**Comment by iykex** [comment]
@iykequame First, file_contexts.bin must be converted to file_contexts, copy it to a mentioned directory with system.new.dat & system.transfer.list , before you can get it unpacked.
so for short, file_contexts.bin is important which u can't bypass 👍

**Comment by qtopie** [comment]
So, for this update.zip file, how can I get file_contexts.bin file?

**Comment by iykex** [comment]
@artificerpi unpack your boot.img , you will find "file_contexts" , use that file to help you extract system.new.dat

**Comment by iykex** [comment]
@artificerpi
I mean the boot.img of that your stock ROM, 
not the update.zip(its boot.img does not contain much files)

**Comment by qtopie** [comment]
File `file_contexts` can be in `/` in android os.
