### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by stainslav** [iykequame/android_system_extraction_and_repack_tool#2]
Sponsored by:

 _____                   _
|_   _| ___  ___  ___  _| | _ _  ___  ___
  | |  | -_||  _|| . || . || | ||   || -_|
  |_|  |___||_|  |__,||___||_  ||_|_||___|

                     *||_http://www.droidpeepz.xyz_||*

                     =================================
            ===!! Android System Extraction/Repack Tool. !!===
                                     For
                     *..MediaTek & Qualcomm Devices..*

                     ========*****************========      
                     *||_http://www.droidpeepz.xyz_||*      

                     =================================
            ===!! Android System Extraction/Repack Tool. !!===
                                     For
                     *..MediaTek & Qualcomm Devices..*

WARNING!  WARNING!! WARNING!!!
Please Check & Trace Where Errors.
 There Is NO rom_system found                               
system.new.dat -->> Missing !

system.transfer.list -->> Missing !

Press enter key to continue . . .

**Comment by iykex** [comment]
@stainslav Make sure that, you copy : system.new.dat & system.transfer.list  to the folder "convert-dat" .
Also, don't forget to convert file_contexts.bin and copy it to convert-dat folder before the system extraction can be done .

Lastly, don't forget to see README

**Comment by stainslav** [comment]
@iykequame hey I'm running it in Lunix emulator GNURoot debian in Android and it seems the path that your script contains is the error how to edit it with my self please answer bro:)
Or 
I mean how to modify your script?

**Comment by iykex** [comment]
@stainslav Sorry, I can't suggest any way.
__I recommend you use PC.__ 
Thanks 

_Sent from my TECNO Camon_C7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by qtopie** [comment]
@iykequame Do you have plan to modify the codes to use relative path rather than the absolute one? I think it might be the cause.

**Comment by iykex** [comment]
@artificerpi sure I can, just that my job is not giving me space to work on the tool.

if you wanna help, you can create and pull request .
👍

**Comment by iykex** [comment]
message me on telegram , username [@zac6ix](https://web.telegram.org/#/im?p=%40zac6ix)
